//******************************** dstmaker.C ********************************//
//                      A part of the rootbeer package                        //
//                                                                            //
//                  Ken Livingstn (k.livingston@physics,gla,ac,uk)            //
//                                                                            //
//      Version         Date                    Comment                       //
//      1               21st Feb 2003                                         //
//      1.2d            23st Mar 2004           Simplified                    //
//      2.0             16th Sep 2005           All in root framework         //
//      2.1             20st Feb 2006           Buf fix edition               //
// ******************************* dstmaker.C ********************************//
// 
// It makes a rootDST from one or more bos or rootDST files
// Can also put hists, or other root things in the output file
// Customize the following
// 1. The line with "char *mybanks[]={....." - this selects the banks to use
// 2. The dropBanks() function - for any used banks to be dropped from DST output
// 3. makeCuts() to decide which events to write to DST
// See http://nuclear.gla.ac.uk/~kl/rootbeer/manual/html/node5.php
// Or the tutorial in doc/manual.ps

#include "RootBeerUtil.h"
#include "TDSTWriter.h"
#include "TH1.h"                // eg. for 1D Histogram                 

class TRootBeer *rootbeer;	// the main BANK file handler object
class TDSTWriter *dstwriter;	// the writer object
class TFile *outFile;           // the file to put the results

int   nEventsTot=0;	       	// ie do all events in all files
int   dstEventCount=0;     	// Events written to DST
char  InFileName[128];	
char  OutFileName[128];	

class   TH1F *taghits;		//example histogram

TRootBeer *createBeerObject();	// create instance of rootbeer Class.
int   dropBanks();		// drop banks (ie not write to DST - MUST CUSTOMIZE)
int   makeCuts();		// cuts - (MUST CUSTOMIZE)
int   closeUp();	        // Close files etc
void  printUsage();
int   parseArgs(int,char **);
void  dstmaker(int, char *, char *);

#ifdef ROOTEXE
int main(int argc,char **argv){
  if((parseArgs(argc,argv))!=0) return(-1);
  dstmaker(nEventsTot,InFileName,OutFileName);
  return(0);
}
#endif

void dstmaker(int nEvents, char *file, char *outFileName){   // The main function

  char 	inFile[128];	       		// holds the current input file name
  int 	fileNo=0;	       		// current file no if sorting though a list
  int   event=0;		    	// Event counter
  int   eventTot=0;	        	// Total event count
  int   lastHeadEvent=0;                // to get event number from HEAD bank

  outFile=new TFile(outFileName,"recreate");  	//Open the output file
  dstwriter = new TDSTWriter(outFile);		//Create the dstwriter
  dropBanks();					//Drop and banks you don't want in DST (CUSTOMIZE BELOW)

  taghits = new TH1F("taghits","taghits",50,0,50); 	//example histogram
  taghits->GetXaxis()->SetTitle("Hits per event"); 	//set axis titles


  // ** DONT FORGET TO DEFINE THE BANKS YOU WANT RIGHT HERE
  // This line can be generated by running:
  // >getbanks -Nevents <BosFile| rootDSTFile>

  char *mybanks[]={"EPIC","SCRC","EVNT","ECPB","SCPB","TAGR","TGBI","DCPB","STPB","MCTK","MCVX","null"};	// make list of banks you want to use

  // ** DONT FORGET TO DEFINE THE BANKS YOU WANT RIGHT HERE
  
  // ********************* Main file loop ***************************************************

  while((fileNo=getNextFile(inFile,file))!=-1){  	// loop while files are still avialable 
    fprintf(stderr,"Sorting file - %s\n",inFile);
    if((rootbeer=createBeerObject(inFile))==NULL) return; // create rootbeer object
    rootbeer->SetBankStatus(mybanks,ON);		//set up the banks
    rootbeer->StartServer();                  		// start the server running
    rootbeer->ListServedBanks();		     	// list the banks which will be served
    dstwriter->Init(rootbeer);				// Init the writer


    // the main sort loop ********************************************************************
    while(event>=0){                                    // do all events
      event = rootbeer->GetEvent();			// get the next event from the server

      if(HEAD[0].NEVENT){                                  //If EVENT no in HEAD = 0, set it to previous one
        lastHeadEvent=HEAD[0].NEVENT;
      }
      else{
        HEAD[0].NEVENT=lastHeadEvent;
      }

      if(makeCuts()==0){	        		// Check passed the cuts
	dstwriter->WriteDST();                     	// Write the event in the Tree
	taghits->Fill(TAGR_NH);				// eg. fill with no of hits in TAGR bank
	dstEventCount++;		     		// increment the count	
      }
      eventTot++;
      if(eventTot%10000 == 0) fprintf(stderr,"Sorted\t%d\tWrote\t%d\n",eventTot,dstEventCount);
      if((nEvents>0)&&(eventTot >=nEvents)) break;		//break if nEvents done
    } 
    //End the main sort loop ****************************************************************

    delete rootbeer;					// delet the rootbeer object
    event = abs(event);
    fprintf(stderr,"Read %d events from %s\n",event,inFile); //print the stats 
    if((nEvents>0)&&(eventTot >=nEvents)) break;	//break if nEvents done
  }

  closeUp();						// close files delete things etc
}

// *************************************************************************** 
//                         CUSTOMIZE THIS FUNCTION                           *
//                                                                           *
//                              TO DROP BANKS                                * 
//                                                                           *
// *************************************************************************** 
//                                                                           *
//                                                                           *

int dropBanks(){
  // Now the ones from the above lot which we DON'T WANT to write out 
  // - for example
  dstwriter->DropBank("SCR ");

  return 0;
}
//                                                                           *
//                                                                           *
// ***************************************************************************
//                                                                           *
//                           END OF BANK DROP                                * 
//                                                                           *
// ***************************************************************************





// *************************************************************************** 
//                         CUSTOMIZE THIS FUNCTION                           *
//                                                                           *
//                         CUTS AND CONDITION FILTER                         * 
//                                                                           *
//             This function has to return 0 to get the event recorded.      *
// *************************************************************************** 
//                                                                           *
//                                                                           *

int makeCuts(){
  //only pass if hits in tagger AND some SCR sector
  // OR an EPIC bank present
  if(((TAGR_NH)&&(SCRC_NS))||EPIC_NS)return 0;
  else return -1;
}

//                                                                           *
//                                                                           *
// *************************************************************************** 
//                                                                           *
//                     END OF CUTS AND CONDITION FILTER                      *
//                                                                           *
// *************************************************************************** 



int parseArgs(int argc,char **argv){
  switch(argc){
  case(1):				// 1 or 2 args not enough
  case(2):
    printUsage();
    return(-1);
    break;
  case(3):				// 3 args dstmaker <infile> <outfile>
    if((strstr(argv[1],"-N"))!=NULL){
      printUsage();
      return(-1);
    }
    else{
      strcpy(InFileName,argv[1]);
      strcpy(OutFileName,argv[2]);
    }
    break;
  case(4):				// 4 args must be "dstmaker -N# <infile> <outfile>" 
    if(strncmp(argv[1],"-N",2)!=0){  	//print usage then exit */
      printUsage();
      return(-1);
    }
    else{
      sscanf(argv[1]+2,"%d",&nEventsTot);	//get the required event no
      strcpy(InFileName,argv[2]);
      strcpy(OutFileName,argv[3]);
    }      
    break;
  default:
    printUsage();
    return(-1);
    break;
  }
  return(0);
}

void printUsage(){
  fprintf(stderr,"\nusage:\n\n");
  fprintf(stderr,"dstmaker -h   Print this message\n\n");
  fprintf(stderr,"dstmaker [-Nevents] <infile> <dstfile> \n");
  fprintf(stderr,"dstmaker [-Nevents] <-Lfilelist> <dstfile> \n");
}


int closeUp(){
  fprintf(stdout,"Wrote %d events to %s\n",dstEventCount,OutFileName);
  delete dstwriter;			// delete the DST writer object
  outFile->Write();			// close the files
  outFile->Close();
  return 0;
}
